### ISSUE TITLE
Realtime Pixel Shader Preview renders black for PS_5_1 to PS_6_1

### ISSUE THREAD

**Issue by ajmiles** [astralis3d/HLSLexplorer#1]
Using this shader:

float4 main() : SV_TARGET
{
    return float4(1,0,0,1);
}

PS_5_0 renders Red, but PS 5_1 and above render black.

**Comment by astralis3d** [comment]
The bug is caused because ID3D11Device::Create...Shader methods support DXBC up to 5.0 version which causes D3D11 error:

D3D11 ERROR: ID3D11Device::CreatePixelShader: Shader must be ps_4_0, ps_4_1, or ps_5_0. Shader version provided: UNRECOGNIZED [ STATE_CREATION ERROR #193: CREATEPIXELSHADER_INVALIDSHADERTYPE]

**Comment by astralis3d** [comment]
Closing. HLSLexplorer 1.01 has D3D12 backend which supports Shader Model 5.1 shaders.
